/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * stdint.h: tipos inteiros de tamanho fixo (uint32_t = inteiro de 32 bits sem
 *           sinal). Em firmware usamos esses tipos porque o tamanho importa: o
 *           registrador do periferico tem 32 bits exatos.
 */
#include <stdint.h>

/*
 * Cabecalhos da biblioteca libopencm3 (camada de drivers que escreve nos
 * registradores do chip por nos):
 *   rcc.h  -> RCC = "Reset and Clock Control". Liga/desliga o clock (o "relogio"
 *             que da energia logica) de cada periferico. No STM32, um periferico
 *             nasce DESLIGADO; sem clock ele nao responde a nada.
 *   gpio.h -> GPIO = "General Purpose Input/Output". Os pinos digitais do chip,
 *             agrupados em portas (GPIOA, GPIOB, GPIOC...), cada uma com 16 pinos.
 */
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>

/*
 * Atraso "burro" por espera ocupada (busy-wait): a CPU simplesmente conta ate
 * gastar tempo. Nao e preciso nem eficiente, mas e o jeito mais simples de
 * comecar (sem timers nem interrupcoes).
 *
 * - O parametro 'n' e quantas voltas o laco da. Quanto maior, maior o atraso.
 * - 'volatile' avisa o compilador: "NAO otimize este laco". Sem 'volatile', o
 *   compilador veria um laco que so decrementa e nao faz nada util, e o
 *   apagaria por completo -- o LED piscaria rapido demais para o olho ver.
 * - __asm__("nop") = "No OPeration", uma instrucao que gasta 1 ciclo sem fazer
 *   nada. Serve so para dar "corpo" ao laco.
 *
 * Observacao: o tempo real depende da frequencia da CPU. Aqui o chip roda no
 * clock interno padrao (HSI) de 8 MHz, pois nao configuramos nada diferente.
 */
static void delay(volatile uint32_t n)
{
    while (n--) {
        __asm__("nop");
    }
}

int main(void)
{
    /*
     * O LED embutido da placa Blue Pill esta ligado ao pino PC13 (pino 13 da
     * porta C). Ele e "ativo em nivel baixo" (active-low): acende quando o pino
     * vai a 0 V e apaga quando vai a 3.3 V -- o contrario do que a intuicao diz.
     * Para so piscar, isso nao muda nada; e bom saber para quando importar.
     */

    /*
     * Passo 1: ligar o clock da porta C. Sem isto, qualquer escrita nos
     * registradores do GPIOC e ignorada pelo hardware.
     */
    rcc_periph_clock_enable(RCC_GPIOC);

    /*
     * Passo 2: configurar o pino PC13 como saida. Os 4 argumentos sao:
     *   GPIOC                    -> em qual porta esta o pino.
     *   GPIO_MODE_OUTPUT_2_MHZ   -> direcao SAIDA, com "velocidade" (slew rate)
     *                               de ate 2 MHz. Para um LED, a opcao mais
     *                               lenta ja basta e gera menos ruido.
     *   GPIO_CNF_OUTPUT_PUSHPULL -> tipo de saida push-pull: o pino consegue
     *                               tanto puxar para 3.3 V quanto para 0 V
     *                               (o oposto seria "open-drain", que so puxa
     *                               para 0 V).
     *   GPIO13                   -> qual(is) pino(s) da porta. E uma mascara de
     *                               bits; daria para configurar varios de uma
     *                               vez com GPIO13 | GPIO14, por exemplo.
     */
    gpio_set_mode(GPIOC, GPIO_MODE_OUTPUT_2_MHZ,
                  GPIO_CNF_OUTPUT_PUSHPULL, GPIO13);

    /*
     * Laco principal e infinito: em firmware bare-metal nao ha sistema
     * operacional para "voltar"; main() nunca deve terminar. Se terminasse, a
     * CPU cairia em comportamento indefinido.
     */
    for (;;) {
        /*
         * gpio_toggle inverte o estado do pino: se estava em 3.3 V vai a 0 V e
         * vice-versa. A cada volta o LED troca entre aceso e apagado.
         */
        gpio_toggle(GPIOC, GPIO13);

        /*
         * Espera entre as trocas. Sem esse atraso, o pino trocaria milhoes de
         * vezes por segundo e o LED pareceria so meio aceso. Ajuste o numero
         * para piscar mais rapido (menor) ou mais devagar (maior).
         */
        delay(100000);
    }
}
